### ISSUE TITLE
Missing repo contents?

### ISSUE THREAD

**Issue by adaruna3** [jtheiner/semantic_geo_partitioning#1]
Hi @jtheiner,

Thanks for providing the code to your visual geolocation paper.

Will you provide code for critical components of the approach? Specifically, the code to perform semantic partitioning? 

Even rough/uncommented python code in a separate branch would help. I ask because I wanted to try training from scratch but it seems there are required input files with no code in the repo to generate them.

Thanks!
Angel

**Comment by ga1i13o** [comment]
I am having the same issue

**Comment by jtheiner** [comment]
Hi @adaruna3, 
unfortunately, I don't have the resources to refactor the partition creation in the near future. I remember networkx showing non-deterministic behavior in dataset preprocessing, graph creation, and partitioning.

You might benefit from the mapping of the training data to the classes as well as pre-trained models that I just uploaded: https://github.com/jtheiner/semantic_geo_partitioning/tree/main/geo_classification#test-on-already-trained-models

**Comment by adaruna3** [comment]
Hi @jtheiner,

No worries! Thanks for the response.

That's excellent! I will take a look at those. 

May have a PR for you shortly.

Thanks again,
Angel
